name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Her gün gece yarısı çalıştırır
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub Username
        run: echo "GITHUB_USERNAME=FDerebag" >> $GITHUB_ENV

      - name: Generate Snake
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: "FDerebag"  # Kullanıcı adı manuel girildi
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          force_orphan: true  # Geçmiş commitleri sıfırlar
